version: 2
project_name: chur

before:
  hooks:
    - go mod tidy

builds:
  - id: webhook
    binary: chur-webhook
    main: ./cmd/webhook
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

  - id: init
    binary: chur-init
    main: ./cmd/init
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - format: tar.gz
    files:
      - LICENSE
      - README.md

dockers:
  - id: webhook
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/lyafence/chur-webhook:{{ .Version }}"
      - "ghcr.io/lyafence/chur-webhook:latest"
    dockerfile: Dockerfile.webhook
    build_flag_templates:
      - "--platform=linux/amd64"

  - id: init
    use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "ghcr.io/lyafence/chur-init:{{ .Version }}"
      - "ghcr.io/lyafence/chur-init:latest"
    dockerfile: Dockerfile.init
    build_flag_templates:
      - "--platform=linux/amd64"

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
