# syntax=docker/dockerfile:1
FROM --platform=$BUILDPLATFORM golang:1.26-alpine AS builder
ARG TARGETOS
ARG TARGETARCH
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -ldflags="-s -w" -o chur-keeper ./cmd/keeper

FROM gcr.io/distroless/static-debian13:nonroot
COPY --from=builder /app/chur-keeper /chur-keeper
EXPOSE 9443 9444
ENTRYPOINT ["/chur-keeper"]
