apiVersion: v2
name: chur
description: Lightweight in-memory secret injection for Kubernetes
type: application
version: 0.0.0
appVersion: "0.0.0"
kubeVersion: ">=1.28.0-0"
home: https://github.com/lyafence/chur
sources:
  - https://github.com/lyafence/chur
keywords:
  - secrets
  - security
  - admission-webhook
  - kubernetes
  - tmpfs
maintainers:
  - name: lyafence
    url: https://github.com/lyafence
