{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chur.fullname" . }}-webhook
  labels:
    {{- include "chur.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: webhook
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - port: {{ .Values.webhook.listen | toString | splitList ":" | last | atoi | default 8443 }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "chur.fullname" . }}-keeper
  labels:
    {{- include "chur.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: keeper
  policyTypes: [Ingress]
  ingress:
    {{- $allowed := .Values.rbac.namespaces }}
    {{- if $allowed }}
    {{- range $ns := $allowed }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $ns }}
      ports:
        - port: {{ $.Values.keeper.listen | toString | splitList ":" | last | atoi | default 9443 }}
    {{- end }}
    {{- else }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Release.Namespace }}
      ports:
        - port: {{ .Values.keeper.listen | toString | splitList ":" | last | atoi | default 9443 }}
    {{- end }}
{{- end }}
