{{- if eq .Values.tls.provider "helmGenerated" }}
{{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.tls.userSecret.name }}
{{- $caCert := "" }}
{{- $tlsCrt := "" }}
{{- $tlsKey := "" }}
{{- if $secret }}
{{- $caCert = index $secret.data "ca.crt" }}
{{- $tlsCrt = index $secret.data "tls.crt" }}
{{- $tlsKey = index $secret.data "tls.key" }}
{{- else }}
{{- $days := int .Values.tls.helmGenerated.validityDays -}}
{{- $ca := genCA "chur-webhook-ca" $days -}}
{{- $svc := include "chur.webhook.serviceName" . -}}
{{- $cert := genSignedCert $svc nil (list $svc) $days $ca -}}
{{- $caCert = $ca.Cert | b64enc }}
{{- $tlsCrt = $cert.Cert | b64enc }}
{{- $tlsKey = $cert.Key | b64enc }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls.userSecret.name }}
  labels:
    {{- include "chur.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $tlsCrt }}
  tls.key: {{ $tlsKey }}
  ca.crt: {{ $caCert }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "chur.fullname" . }}-webhook
  labels:
    {{- include "chur.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "chur.webhook.serviceName" . }}
    clientConfig:
      service:
        name: {{ include "chur.fullname" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /
        port: {{ .Values.service.port }}
      caBundle: {{ $caCert }}
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    sideEffects: None
    admissionReviewVersions: ["v1"]
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds }}
    reinvocationPolicy: IfNeeded
    {{- include "chur.webhook.namespaceSelector" . | nindent 4 }}
{{- end }}
